### ISSUE TITLE
make serve Error 1 

### ISSUE THREAD

**Issue by tameek** [swcarpentry/shell-novice#1299]
Excuse the huge block of text below, but in summary, `make serve` failed on calling

```/opt/homebrew/lib/ruby/gems/3.1.0/bin/jekyll```

As you can see here I do have Jekyll installed:

```
~$ bundle info jekyll
  * jekyll (3.9.2)
	Summary: A simple, blog aware, static site generator.
	Homepage: https://github.com/jekyll/jekyll
	Path: /opt/homebrew/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2
```

this Rubygem was installed view HomeBrew.

Per Ruby's [documentation](https://www.ruby-lang.org/en/documentation/installation/#homebrew), this is the instructed way to install Ruby

Note sure what the issue is here.  I may be able to look into this more deeply on a Friday.  Has anyone else seen this error?

```
~$ make serve
bundle config --local set path .vendor/bundle && bundle install && bundle update && bundle exec jekyll serve --config _config.yml,./_includes/snippets_library/ComputeCanada_Graham_slurm/_config_options.yml
Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies....
Using bundler 2.3.11
Using minitest 5.15.0
Fetching zeitwerk 2.5.4
Fetching thread_safe 0.3.6
Fetching execjs 2.8.1
Fetching commonmarker 0.23.4
Fetching colorator 1.1.0
Fetching concurrent-ruby 1.1.10
Fetching coffee-script-source 1.11.1
Fetching public_suffix 4.0.7
Installing execjs 2.8.1
Installing colorator 1.1.0
Installing zeitwerk 2.5.4
Installing coffee-script-source 1.11.1
Installing public_suffix 4.0.7
Installing thread_safe 0.3.6
Installing commonmarker 0.23.4 with native extensions
Fetching unf_ext 0.0.8.1
Fetching eventmachine 1.2.7
Installing concurrent-ruby 1.1.10
Fetching http_parser.rb 0.8.0
Fetching ffi 1.15.5
Fetching faraday-em_http 1.0.0
Fetching faraday-em_synchrony 1.0.0
Installing eventmachine 1.2.7 with native extensions
Installing unf_ext 0.0.8.1 with native extensions
Installing faraday-em_http 1.0.0
Installing http_parser.rb 0.8.0 with native extensions
Fetching faraday-excon 1.1.0
Installing faraday-em_synchrony 1.0.0
Fetching faraday-httpclient 1.0.1
Installing faraday-excon 1.1.0
Fetching multipart-post 2.1.1
Installing faraday-httpclient 1.0.1
Fetching faraday-net_http 1.0.1
Installing multipart-post 2.1.1
Installing faraday-net_http 1.0.1
Fetching faraday-net_http_persistent 1.2.0
Fetching faraday-patron 1.0.0
Installing ffi 1.15.5 with native extensions
Fetching faraday-rack 1.0.0
Installing faraday-patron 1.0.0
Installing faraday-net_http_persistent 1.2.0
Using ruby2_keywords 0.0.5
Fetching forwardable-extended 2.6.0
Fetching faraday-retry 1.0.3
Installing faraday-rack 1.0.0
Fetching gemoji 3.0.1
Installing faraday-retry 1.0.3
Fetching rb-fsevent 0.11.1
Installing gemoji 3.0.1
Installing forwardable-extended 2.6.0
Using rexml 3.2.5
Fetching liquid 4.0.3
Installing rb-fsevent 0.11.1
Fetching mercenary 0.3.6
Installing liquid 4.0.3
Installing mercenary 0.3.6
Fetching rouge 3.26.0
Fetching safe_yaml 1.0.5
Using racc 1.6.0
Fetching jekyll-paginate 1.1.0
Installing safe_yaml 1.0.5
Fetching rubyzip 2.3.2
Installing jekyll-paginate 1.1.0
Installing rouge 3.26.0
Fetching jekyll-swiss 1.0.0
Installing rubyzip 2.3.2
Fetching unicode-display_width 1.8.0
Installing jekyll-swiss 1.0.0
Fetching mixlib-cli 2.1.8
Installing unicode-display_width 1.8.0
Fetching tomlrb 2.0.1
Installing mixlib-cli 2.1.8
Installing tomlrb 2.0.1
Fetching coffee-script 2.4.1
Fetching addressable 2.8.0
Installing coffee-script 2.4.1
Fetching tzinfo 1.2.9
Installing addressable 2.8.0
Fetching faraday-multipart 1.0.3
Installing tzinfo 1.2.9
Fetching i18n 0.9.5
Installing faraday-multipart 1.0.3
Fetching chef-utils 17.10.0
Fetching kramdown 2.3.2
Installing i18n 0.9.5
Installing chef-utils 17.10.0
Installing kramdown 2.3.2
Fetching pathutil 0.16.2
Fetching nokogiri 1.13.6 (arm64-darwin)
Fetching terminal-table 1.8.0
Installing terminal-table 1.8.0
Fetching mixlib-config 3.0.9
Installing pathutil 0.16.2
Fetching jekyll-coffeescript 1.1.1
Installing mixlib-config 3.0.9
Fetching faraday 1.10.0
Fetching mixlib-shellout 3.2.7
Installing jekyll-coffeescript 1.1.1
Installing faraday 1.10.0
Installing mixlib-shellout 3.2.7
Fetching activesupport 6.0.5
Fetching kramdown-parser-gfm 1.1.0
Fetching sawyer 0.8.2
Installing kramdown-parser-gfm 1.1.0
Installing activesupport 6.0.5
Fetching mdl 0.11.0
Installing sawyer 0.8.2
Fetching octokit 4.22.0
Installing mdl 0.11.0
Installing octokit 4.22.0
Fetching unf 0.1.4
Installing nokogiri 1.13.6 (arm64-darwin)
Fetching jekyll-gist 1.5.0
Installing unf 0.1.4
Fetching simpleidn 0.2.1
Installing jekyll-gist 1.5.0
Installing simpleidn 0.2.1
Fetching dnsruby 1.61.9
Installing dnsruby 1.61.9
Fetching html-pipeline 2.14.1
Installing html-pipeline 2.14.1
Fetching jekyll-commonmark 1.4.0
Installing jekyll-commonmark 1.4.0
Fetching ethon 0.15.0
Fetching rb-inotify 0.10.1
Installing rb-inotify 0.10.1
Fetching sass-listen 4.0.0
Fetching listen 3.7.1
Installing ethon 0.15.0
Fetching typhoeus 1.4.0
Installing sass-listen 4.0.0
Fetching sass 3.7.4
Installing listen 3.7.1
Fetching jekyll-watch 2.2.1
Installing typhoeus 1.4.0
Fetching github-pages-health-check 1.17.9
Installing jekyll-watch 2.2.1
Installing sass 3.7.4
Installing github-pages-health-check 1.17.9
Fetching jekyll-sass-converter 1.5.2
Installing jekyll-sass-converter 1.5.2
Fetching em-websocket 0.5.3
Installing em-websocket 0.5.3
Fetching jekyll 3.9.2
Installing jekyll 3.9.2
Fetching jekyll-mentions 1.6.0
Fetching jekyll-commonmark-ghpages 0.2.0
Fetching jekyll-include-cache 0.2.1
Fetching jekyll-optional-front-matter 0.3.2
Fetching jekyll-default-layout 0.1.4
Fetching jekyll-avatar 0.7.0
Fetching jekyll-feed 0.15.1
Fetching jekyll-github-metadata 2.13.0
Installing jekyll-mentions 1.6.0
Fetching jekyll-readme-index 0.3.0
Installing jekyll-include-cache 0.2.1
Installing jekyll-commonmark-ghpages 0.2.0
Installing jekyll-feed 0.15.1
Installing jekyll-avatar 0.7.0
Installing jekyll-default-layout 0.1.4
Fetching jekyll-redirect-from 0.16.0
Installing jekyll-github-metadata 2.13.0
Installing jekyll-optional-front-matter 0.3.2
Installing jekyll-readme-index 0.3.0
Fetching jekyll-relative-links 0.6.1
Fetching jekyll-remote-theme 0.4.3
Fetching jekyll-seo-tag 2.8.0
Fetching jekyll-sitemap 1.4.0
Installing jekyll-redirect-from 0.16.0
Fetching jekyll-titles-from-headings 0.5.3
Fetching jemoji 0.12.0
Installing jekyll-remote-theme 0.4.3
Installing jekyll-seo-tag 2.8.0
Installing jekyll-titles-from-headings 0.5.3
Installing jemoji 0.12.0
Fetching jekyll-theme-architect 0.2.0
Fetching jekyll-theme-cayman 0.2.0
Fetching jekyll-theme-hacker 0.2.0
Fetching jekyll-theme-dinky 0.2.0
Installing jekyll-sitemap 1.4.0
Fetching jekyll-theme-leap-day 0.2.0
Fetching jekyll-theme-merlot 0.2.0
Installing jekyll-relative-links 0.6.1
Installing jekyll-theme-cayman 0.2.0
Installing jekyll-theme-dinky 0.2.0
Installing jekyll-theme-hacker 0.2.0
Fetching jekyll-theme-midnight 0.2.0
Installing jekyll-theme-architect 0.2.0
Fetching jekyll-theme-minimal 0.2.0
Fetching jekyll-theme-modernist 0.2.0
Fetching jekyll-theme-primer 0.6.0
Installing jekyll-theme-modernist 0.2.0
Fetching jekyll-theme-slate 0.2.0
Installing jekyll-theme-primer 0.6.0
Fetching jekyll-theme-tactile 0.2.0
Installing jekyll-theme-merlot 0.2.0
Installing jekyll-theme-minimal 0.2.0
Installing jekyll-theme-slate 0.2.0
Installing jekyll-theme-leap-day 0.2.0
Fetching jekyll-theme-time-machine 0.2.0
Installing jekyll-theme-tactile 0.2.0
Fetching minima 2.5.1
Installing jekyll-theme-time-machine 0.2.0
Installing minima 2.5.1
Installing jekyll-theme-midnight 0.2.0
Fetching github-pages 226
Installing github-pages 226
Bundle complete! 3 Gemfile dependencies, 107 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
Post-install message from dnsruby:
Installing dnsruby...
  For issues and source code: https://github.com/alexdalitz/dnsruby
  For general discussion (please tell us how you use dnsruby): https://groups.google.com/forum/#!forum/dnsruby
Post-install message from sass:

Ruby Sass has reached end-of-life and should no longer be used.

* If you use Sass as a command-line tool, we recommend using Dart Sass, the new
  primary implementation: https://sass-lang.com/install

* If you use Sass as a plug-in for a Ruby web framework, we recommend using the
  sassc gem: https://github.com/sass/sassc-ruby#readme

* For more details, please refer to the Sass blog:
  https://sass-lang.com/blog/posts/7828841

Post-install message from html-pipeline:
-------------------------------------------------
Thank you for installing html-pipeline!
You must bundle Filter gem dependencies.
See html-pipeline README.md for more details.
https://github.com/jch/html-pipeline#dependencies
-------------------------------------------------
Post-install message from rubyzip:
RubyZip 3.0 is coming!
**********************

The public API of some Rubyzip classes has been modernized to use named
parameters for optional arguments. Please check your usage of the
following classes:
  * `Zip::File`
  * `Zip::Entry`
  * `Zip::InputStream`
  * `Zip::OutputStream`

Please ensure that your Gemfiles and .gemspecs are suitably restrictive
to avoid an unexpected breakage when 3.0 is released (e.g. ~> 2.3.0).
See https://github.com/rubyzip/rubyzip for details. The Changelog also
lists other enhancements and bugfixes that have been implemented since
version 2.3.0.
Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies...
Using concurrent-ruby 1.1.10
Using zeitwerk 2.5.4
Using public_suffix 4.0.7
Using bundler 2.3.11
Using colorator 1.1.0
Using minitest 5.15.0
Using thread_safe 0.3.6
Using coffee-script-source 1.11.1
Using execjs 2.8.1
Using commonmarker 0.23.4
Using unf_ext 0.0.8.1
Using eventmachine 1.2.7
Using http_parser.rb 0.8.0
Using ffi 1.15.5
Using faraday-em_http 1.0.0
Using faraday-em_synchrony 1.0.0
Using faraday-excon 1.1.0
Using faraday-httpclient 1.0.1
Using multipart-post 2.1.1
Using faraday-net_http 1.0.1
Using faraday-net_http_persistent 1.2.0
Using faraday-patron 1.0.0
Using faraday-retry 1.0.3
Using ruby2_keywords 0.0.5
Using forwardable-extended 2.6.0
Using rb-fsevent 0.11.1
Using rexml 3.2.5
Using liquid 4.0.3
Using mercenary 0.3.6
Using rouge 3.26.0
Using safe_yaml 1.0.5
Using racc 1.6.0
Using jekyll-swiss 1.0.0
Using faraday-rack 1.0.0
Using gemoji 3.0.1
Using tomlrb 2.0.1
Using i18n 0.9.5
Using chef-utils 17.10.0
Using unf 0.1.4
Using em-websocket 0.5.3
Using ethon 0.15.0
Using faraday-multipart 1.0.3
Using rb-inotify 0.10.1
Using kramdown 2.3.2
Using pathutil 0.16.2
Using nokogiri 1.13.6 (arm64-darwin)
Using tzinfo 1.2.9
Using jekyll-paginate 1.1.0
Using unicode-display_width 1.8.0
Using activesupport 6.0.5
Using typhoeus 1.4.0
Using sass-listen 4.0.0
Using listen 3.7.1
Using kramdown-parser-gfm 1.1.0
Using mixlib-config 3.0.9
Using faraday 1.10.0
Using addressable 2.8.0
Using sass 3.7.4
Using jekyll-watch 2.2.1
Using html-pipeline 2.14.1
Using rubyzip 2.3.2
Using sawyer 0.8.2
Using jekyll-sass-converter 1.5.2
Using mixlib-cli 2.1.8
Using jekyll-commonmark 1.4.0
Using mixlib-shellout 3.2.7
Using simpleidn 0.2.1
Using jekyll 3.9.2
Using mdl 0.11.0
Using octokit 4.22.0
Using terminal-table 1.8.0
Using jekyll-avatar 0.7.0
Using jekyll-commonmark-ghpages 0.2.0
Using jekyll-feed 0.15.1
Using jekyll-gist 1.5.0
Using jekyll-github-metadata 2.13.0
Using jekyll-include-cache 0.2.1
Using jekyll-mentions 1.6.0
Using jekyll-optional-front-matter 0.3.2
Using jekyll-readme-index 0.3.0
Using jekyll-redirect-from 0.16.0
Using jekyll-relative-links 0.6.1
Using jekyll-seo-tag 2.8.0
Using jekyll-sitemap 1.4.0
Using jekyll-titles-from-headings 0.5.3
Using jemoji 0.12.0
Using jekyll-theme-cayman 0.2.0
Using jekyll-theme-dinky 0.2.0
Using coffee-script 2.4.1
Using jekyll-theme-midnight 0.2.0
Using jekyll-theme-minimal 0.2.0
Using jekyll-theme-modernist 0.2.0
Using jekyll-theme-primer 0.6.0
Using jekyll-theme-slate 0.2.0
Using jekyll-theme-tactile 0.2.0
Using jekyll-theme-time-machine 0.2.0
Using minima 2.5.1
Using jekyll-theme-architect 0.2.0
Using jekyll-coffeescript 1.1.1
Using dnsruby 1.61.9
Using jekyll-default-layout 0.1.4
Using github-pages-health-check 1.17.9
Using jekyll-theme-hacker 0.2.0
Using jekyll-theme-merlot 0.2.0
Using jekyll-remote-theme 0.4.3
Using jekyll-theme-leap-day 0.2.0
Using github-pages 226
Bundle updated!
Configuration file: _config.yml
Configuration file: ./_includes/snippets_library/ComputeCanada_Graham_slurm/_config_options.yml
            Source: /Users/tameek/hpc-intro
       Destination: /Users/tameek/hpc-intro/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
      Remote Theme: Using theme carpentries/carpentries-theme
                    done in 0.959 seconds.
 Auto-regeneration: enabled for '/Users/tameek/hpc-intro'
bundler: failed to load command: jekyll (/opt/homebrew/lib/ruby/gems/3.1.0/bin/jekyll)
/opt/homebrew/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/lib/jekyll/commands/serve/servlet.rb:3:in `require': cannot load such file -- webrick (LoadError)
	from /opt/homebrew/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/lib/jekyll/commands/serve/servlet.rb:3:in `<top (required)>'
	from /opt/homebrew/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:184:in `require_relative'
	from /opt/homebrew/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:184:in `setup'
	from /opt/homebrew/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:102:in `process'
	from /opt/homebrew/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:93:in `block in start'
	from /opt/homebrew/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:93:in `each'
	from /opt/homebrew/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:93:in `start'
	from /opt/homebrew/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
	from /opt/homebrew/lib/ruby/gems/3.1.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /opt/homebrew/lib/ruby/gems/3.1.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /opt/homebrew/lib/ruby/gems/3.1.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /opt/homebrew/lib/ruby/gems/3.1.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /opt/homebrew/lib/ruby/gems/3.1.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /opt/homebrew/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/exe/jekyll:15:in `<top (required)>'
	from /opt/homebrew/lib/ruby/gems/3.1.0/bin/jekyll:25:in `load'
	from /opt/homebrew/lib/ruby/gems/3.1.0/bin/jekyll:25:in `<top (required)>'
	from /opt/homebrew/Cellar/ruby/3.1.2/lib/ruby/3.1.0/bundler/cli/exec.rb:58:in `load'
	from /opt/homebrew/Cellar/ruby/3.1.2/lib/ruby/3.1.0/bundler/cli/exec.rb:58:in `kernel_load'
	from /opt/homebrew/Cellar/ruby/3.1.2/lib/ruby/3.1.0/bundler/cli/exec.rb:23:in `run'
	from /opt/homebrew/Cellar/ruby/3.1.2/lib/ruby/3.1.0/bundler/cli.rb:483:in `exec'
	from /opt/homebrew/Cellar/ruby/3.1.2/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /opt/homebrew/Cellar/ruby/3.1.2/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /opt/homebrew/Cellar/ruby/3.1.2/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /opt/homebrew/Cellar/ruby/3.1.2/lib/ruby/3.1.0/bundler/cli.rb:31:in `dispatch'
	from /opt/homebrew/Cellar/ruby/3.1.2/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /opt/homebrew/Cellar/ruby/3.1.2/lib/ruby/3.1.0/bundler/cli.rb:25:in `start'
	from /opt/homebrew/Cellar/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.11/exe/bundle:48:in `block in <top (required)>'
	from /opt/homebrew/Cellar/ruby/3.1.2/lib/ruby/3.1.0/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	from /opt/homebrew/Cellar/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.11/exe/bundle:36:in `<top (required)>'
	from /opt/homebrew/opt/ruby/bin/bundle:25:in `load'
	from /opt/homebrew/opt/ruby/bin/bundle:25:in `<main>'
make: *** [serve] Error 1
```

**Comment by fmichonneau** [comment]
Hi @tameek,

You have this error because you need to install manually the webrick gem. 

Prior to Ruby 3, it wasn't needed, and GitHub pages pins Ruby to version 2.7.3 (https://pages.github.com/versions/). We added some code in the Gemfile to detect when the version of Ruby requires it and install it but it doesn't seem to work for you.

Here are a few things to try:
- if you have a `Gemfile.lock` delete it, and then re-run `make serve`
- manually install `webrick` with `bundle exec gem install webrick`

If this fails, you could try to remove ruby 3.1.0 and install ruby 2.7.6 with homebrew: `brew install ruby@2.7`

**Comment by bkmgit** [comment]
Removing `Gemfile.lock` and then adding webrick to the Gemfile and installing works. Closing as transitioning to workbench.
